### PR TITLE
#187 & #193: Prevent repeated action executions

### PR DESCRIPTION
**Pull request by BR0kEN-**
Resolves:
- https://github.com/agiledivider/vagrant-hostsupdater/issues/187
- https://github.com/agiledivider/vagrant-hostsupdater/issues/193

For those who interested in applying the fix without waiting for the new release:

```
cd ~/.vagrant.d/gems/<VERSION>/gems/vagrant-hostsupdater-1.2.1
curl -sSL https://github.com/agiledivider/vagrant-hostsupdater/pull/197.patch -o 197.patch
patch -p1 < 197.patch
```

### CODE REVIEW

**Comment by fukasugi** [comment]
I appreciate it much!
Thank you.

**Comment by theodore86** [comment]
Tested on Windows 10 and Linux/Ubuntu OS, works great!

Thank you very much!

**Comment by siliconmeadow** [comment]
Hi @BR0kEN- 

Would you consider asking @cgsmith if you could take this project over?

**Comment by cgsmith** [comment]
@siliconmeadow I am not the owner of the repo. You'll need to fork it and build it out from their.

**Comment by BR0kEN-** [comment]
Ping @agiledivider

**Comment by cgsmith** [comment]
@BR0kEN- good luck with that. He hasn't been involved in the project for a while. I suggest forking and starting a different one.

**Pull request merged**
